### ISSUE TITLE
Creating a license: Datepicker for purchase date is diffferent from all other datepickers

### ISSUE THREAD

**Issue by dmeltzer** [snipe/snipe-it-laravel5#18]
Last one for now!

The datepicker for purchase date doesn't have the up and down arrows to adjust the date.  I'm not sure which option is better, but I do know this one is different.

**Comment by snipe** [comment]
![shhhhh](https://cloud.githubusercontent.com/assets/197404/13515269/f0a036ce-e164-11e5-8dc7-590f1887ab32.gif)

**Comment by snipe** [comment]
What browser?

These look the same to me.

<img width="516" alt="screen shot 2016-03-03 at 5 30 10 pm" src="https://cloud.githubusercontent.com/assets/197404/13515381/b1d7a9e4-e165-11e5-94f1-57eb76c3265b.png">
<img width="465" alt="screen shot 2016-03-03 at 5 30 18 pm" src="https://cloud.githubusercontent.com/assets/197404/13515380/b1d07a5c-e165-11e5-8698-6c58e9eef991.png">
<img width="508" alt="screen shot 2016-03-03 at 5 30 24 pm" src="https://cloud.githubusercontent.com/assets/197404/13515387/bb1df896-e165-11e5-9e1e-c5eeeecbc542.png">
