### ISSUE TITLE
v3 request - Add Groups column to License Detail view

### ISSUE THREAD

**Issue by jghanlon** [snipe/snipe-it-laravel5#20]
v3 request - Add Groups column to this page: https://v3.snipeitapp.com/admin/licenses/3/view
To the right of the "Assets" column.

reason: it is helpful to know how many seats of a volume license belong to each department

**Comment by snipe** [comment]
Can you please create this on the primary repo? I'm not taking feature requests on this one. They'll just get lost when I merge this repo into the other.

**Comment by jghanlon** [comment]
moved to #1822

**Comment by snipe** [comment]
Thanks!
